name: Publish
on:
  push:
    branches: [ dev ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install and use custom node version
        run: npm i -g npm@7
      - name: Package restore
        run: npm install
      - name: Build site
        run: npm run build
      - name: Deploy site
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs_deploy
          publish_branch: master
